# Generated by Django 3.0.5 on 2020-04-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Coviddata',
        ),
    ]
